name: collaborative_knowledge_board
description: A scalable collaborative board app built with Clean Architecture.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

# ------------------------------------------------
# DEPENDENCIES
# ------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.0.0

  # --------------------------
  # STATE MANAGEMENT
  # --------------------------
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # --------------------------
  # ROUTING
  # --------------------------
  go_router: ^13.2.4

  # --------------------------
  # NETWORK
  # --------------------------
  dio: ^5.4.3+1

  # --------------------------
  # SECURE STORAGE
  # --------------------------
  flutter_secure_storage: ^9.2.2

  # --------------------------
  # JSON SERIALIZATION
  # --------------------------
  json_annotation: ^4.9.0

  # --------------------------
  # IMMUTABLE MODELS
  # --------------------------
  freezed_annotation: ^2.4.1

  # --------------------------
  # UTILITIES
  # --------------------------
  equatable: ^2.0.5
  intl: ^0.19.0
  uuid: ^4.4.0

  # --------------------------
  # UI
  # --------------------------
  flutter_hooks: ^0.20.5

  # Icons
  cupertino_icons: ^1.0.6

  dartz: ^0.10.1

# ------------------------------------------------
# DEV DEPENDENCIES
# ------------------------------------------------

dev_dependencies:

  # Faker
  faker: ^2.1.0

  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.2

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

  # Testing
  mocktail: ^1.0.3

# ------------------------------------------------
# FLUTTER CONFIG
# ------------------------------------------------

flutter:
  uses-material-design: true

  # Assets (cuando agregues)
  #assets:
    #- assets/images/
    #- assets/icons/